name: NodeJS Continuous Health Check

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "documentation/**"
      - "README.md"
      - "errors.log"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "documentation/**"
      - "README.md"
      - "errors.log"

jobs:
  node_ci:
    runs-on: ${{ matrix.os }}
    env:
      NODE_CACHE: "npm"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      -
        name: Check out repository
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
      -
        name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: false
          registry-url: https://registry.npmjs.org
          # cache: ${{ env.NODE_CACHE }}
          # cache-dependency-path: ${{ matrix.dir }}/package-lock.json
      -
        name: Cleanup for node > 16
        if: ${{ matrix.node!='16' }}
        shell: bash -e -l {0}
        run: |
          sh wipe.sh
          npm i --package-lock --no-audit
      -
        name: Build workspace
        shell: bash -e -l {0}
        run: |
          npm ci --prefer-offline --no-audit
          npm run --if-present build
          npm run --if-present cilint
